services:
  - type: web
    name: kindra-backend
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerFilePath: ./backend/Dockerfile
    dockerContext: ./backend
    numReplicas: 1
    envVars:
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: kindra-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: kindra-db
    plan: free
    region: oregon
